version: '3.9'

services:
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Password1'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_LOG_DIR: /var/opt/mssql/log
      MSSQL_BACKUP_DIR: /var/opt/mssql/backup
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
  
  novafinds-api:
    container_name: novafinds-api
    hostname: novafinds-api
    build:
      context: .
      dockerfile: Dockerfile_API
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: true
      ASPNETCORE_HTTP_PORTS: 8080
      DOTNET_RUNNING_IN_CONTAINER: true
      DOTNET_VERSION: 8.0.2
      ASPNET_VERSION: 8.0.2
    ports:
      - "8080:8080"

  novafinds-mvc:
    container_name: novafinds-mvc
    hostname: novafinds-mvc
    build:
      context: .
      dockerfile: Dockerfile_MVC
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: true
      ASPNETCORE_HTTP_PORTS: 8080
      DOTNET_RUNNING_IN_CONTAINER: true
      DOTNET_VERSION: 8.0.2
      ASPNET_VERSION: 8.0.2
    ports:
      - "8081:8080"

volumes:
  db_data:
    driver: local